{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.6.1.aar",
          "url": "media3-decode-opus-1.6.1.aar",
          "size": 513700,
          "sha512": "eb4b0994f8c3d1bf3a20e08d2043a34c6e36a470f94242252c24b61b0e15ef78043a3feb289f0290fdd653b77c60c50e5a6f87f8d5285e375160d2d9c68e1032",
          "sha256": "2fa306ee8582c729c69691195201a76fcce933098c463af1f78df7a31ee4ad49",
          "sha1": "b159519449c1673d512a811cb5d1f45f39825f8e",
          "md5": "c89ac6638cdefb74f83fb2a887255d88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.6.1.aar",
          "url": "media3-decode-opus-1.6.1.aar",
          "size": 513700,
          "sha512": "eb4b0994f8c3d1bf3a20e08d2043a34c6e36a470f94242252c24b61b0e15ef78043a3feb289f0290fdd653b77c60c50e5a6f87f8d5285e375160d2d9c68e1032",
          "sha256": "2fa306ee8582c729c69691195201a76fcce933098c463af1f78df7a31ee4ad49",
          "sha1": "b159519449c1673d512a811cb5d1f45f39825f8e",
          "md5": "c89ac6638cdefb74f83fb2a887255d88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.6.1-sources.jar",
          "url": "media3-decode-opus-1.6.1-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
